name: Devcontainer

on:
  push:
    paths:
      - .devcontainer/**
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/skolorna/euphemism-devcontainer
          tags: |
            type=schedule
            type=sha
          flavor: |
            latest=true
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/skolorna/euphemism-devcontainer:latest
          context: .devcontainer
          push: true
          tags: ${{ steps.meta.outputs.tags }}
